# Generated by Django 4.0.2 on 2022-02-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('fulladdress', models.CharField(max_length=10000)),
                ('data', models.CharField(max_length=10000)),
            ],
        ),
    ]
