# Generated by Django 4.0.2 on 2022-02-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistor', '0002_filedata_remove_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='body',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='filedata',
            name='text_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='filedata',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='filedata',
            name='userId',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='filedata',
            name='username',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
