# Generated by Django 4.0.2 on 2022-02-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistor', '0003_filedata_body_filedata_text_id_filedata_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='text_id',
        ),
        migrations.AlterField(
            model_name='filedata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
